name: Dev Docker Build & Push

on:
  push:
    branches:
      - dev

jobs:
  build:
    strategy:
      matrix:
        architecture: [arm64, amd64]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: registry.zec.one
          username: ${{ secrets.REGISTRY_ZEC_ONE_USERNAME }}
          password: ${{ secrets.REGISTRY_ZEC_ONE_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/${{ matrix.architecture }} \
            -t registry.zec.one/charge-controller-dev:${{ matrix.architecture }}-latest .
          docker push registry.zec.one/charge-controller-dev:${{ matrix.architecture }}-latest
