name: dev docker build & push

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Git info
        run: |
          echo "COMMITID=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "BRANCH=$(git symbolic-ref --short HEAD)" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: davbauer
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        run: |
          docker buildx version
          docker buildx create --use

      - name: Dockerize and Push Image to GHCR
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ghcr.io/davbauer/charge-controller-dev:latest
          build-args: |
            COMMITID=${{ env.COMMITID }}
            BRANCH=${{ env.BRANCH }}
