name: dev docker build & push

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: registry.zec.one
          username: ${{ secrets.REGISTRY_ZEC_ONE_USERNAME }}
          password: ${{ secrets.REGISTRY_ZEC_ONE_PASSWORD }}

      - name: Set up Docker Buildx
        run: |
          docker buildx version
          docker buildx create --use

      - name: Dockerize and Push Image
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/arm64,linux/amd64
          tags: registry.zec.one/charge-controller-dev
